### ISSUE TITLE
ESLint and coding standards

### ISSUE THREAD

**Issue by mourner** [tcql/greiner-hormann#11]
The repo lacks a consistent coding style. It's also generally very useful to lint code because it often uncovers potential bugs. 

http://eslint.org/ is awesome. Here's a sample config: https://github.com/mapbox/earcut/blob/master/.eslintrc

**Comment by tcql** [comment]
Thanks for the helpful feedback :) I'll work on getting eslint incorporated in the near future, and then clean it all up :tada:

**Comment by tcql** [comment]
finished in 4558ec5, ca0b068, and 2299e5c

**Comment by mourner** [comment]
Looks great!
