### ISSUE TITLE
bump npm published version

### ISSUE THREAD

**Issue by anandthakker** [tcql/greiner-hormann#12]
Trying out your `kill-jsts` branch of `turf-intersect`, and it's getting the version of this module before the extra logs were removed in 7816929fc435f0a52158b75ef22cccbc8eacf5fd.  Any chance you could tag a new release?

**Comment by tcql** [comment]
Sorry for the delay on this - this issue got buried in a flood of github notifications. I've bumped to 0.3.3

**Comment by anandthakker** [comment]
@tchannel no worries, and thanks!
